// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lmifuqesostqcfyshtdl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxtaWZ1cWVzb3N0cWNmeXNodGRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0Mzc5NDgsImV4cCI6MjA2MjAxMzk0OH0.yhX5PMdiyOy0Qfi1X21vNE3OK5RTKgO2RMoAo0--8ew";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);